=== Avzgui/C.C.S/ConnectedCarsSimulator/src/Utility/CCS_Environment.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Elements' definition -->
<!ELEMENT network (intersection|road)+>
<!ELEMENT intersection (indonesian, cardinal, cardinal, cardinal, cardinal)>
<!ELEMENT road (cardinal, cardinal)>
<!ELEMENT indonesian (#PCDATA)>
<!ELEMENT cardinal (flow, flow)>
<!ELEMENT flow (ways, size)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT ways (#PCDATA)>

<!-- Elements' attributes -->
<!ATTLIST intersection 
    x CDATA #REQUIRED
    y CDATA #REQUIRED
>

<!ATTLIST road 
    x CDATA #REQUIRED
    y CDATA #REQUIRED
>

<!ATTLIST cardinal 
    type (north|east|south|west) #REQUIRED
>

<!ATTLIST flow 
    type (in|out) #REQUIRED
>

=== Avzgui/C.C.S/ConnectedCarsSimulator/save/environments/ASimpleIntersection.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE network SYSTEM "../../src/Utility/CCS_Environment.dtd">

<network>
    <intersection x="0" y="0">
        <indonesian>true</indonesian>
        <cardinal type="north">
            <flow type="in">
                <ways>3</ways>
                <size>8</size>
            </flow>
            <flow type="out">
                <ways>3</ways>
                <size>8</size>
            </flow>
        </cardinal>
        <cardinal type="east">
            <flow type="in">
                <ways>3</ways>
                <size>8</size>
            </flow>
            <flow type="out">
                <ways>3</ways>
                <size>8</size>
            </flow>
        </cardinal>
        <cardinal type="south">
            <flow type="in">
                <ways>3</ways>
                <size>8</size>
            </flow>
            <flow type="out">
                <ways>3</ways>
                <size>8</size>
            </flow>
        </cardinal>
        <cardinal type="west">
            <flow type="in">
                <ways>3</ways>
                <size>8</size>
            </flow>
            <flow type="out">
                <ways>3</ways>
                <size>8</size>
            </flow>
        </cardinal>
    </intersection>
</network>
